import { Attribute, AttributeCategory } from '../types'

// Mock data for 600+ attributes organized by categories
export const ATTRIBUTE_CATEGORIES: AttributeCategory[] = [
  'Identity & Contact',
  'Demographics',
  'Financial & Wealth',
  'Home & Property',
  'Professional',
  'Lifestyle',
  'Technology',
  'Marketing',
]

export const ALL_ATTRIBUTES: Attribute[] = [
  // Identity & Contact (80 attributes)
  { id: '1', name: 'First Name', category: 'Identity & Contact', type: 'categorical' },
  { id: '2', name: 'Last Name', category: 'Identity & Contact', type: 'categorical' },
  { id: '3', name: 'Full Name', category: 'Identity & Contact', type: 'categorical' },
  { id: '4', name: 'Email Address', category: 'Identity & Contact', type: 'categorical' },
  { id: '5', name: 'Phone Number', category: 'Identity & Contact', type: 'categorical' },
  { id: '6', name: 'Mobile Phone', category: 'Identity & Contact', type: 'categorical' },
  { id: '7', name: 'Work Phone', category: 'Identity & Contact', type: 'categorical' },
  { id: '8', name: 'Home Phone', category: 'Identity & Contact', type: 'categorical' },
  { id: '9', name: 'Street Address', category: 'Identity & Contact', type: 'categorical' },
  { id: '10', name: 'City', category: 'Identity & Contact', type: 'categorical' },
  { id: '11', name: 'State', category: 'Identity & Contact', type: 'categorical' },
  { id: '12', name: 'ZIP Code', category: 'Identity & Contact', type: 'categorical' },
  { id: '13', name: 'Country', category: 'Identity & Contact', type: 'categorical' },
  { id: '14', name: 'IP Address', category: 'Identity & Contact', type: 'categorical' },
  { id: '15', name: 'Device ID', category: 'Identity & Contact', type: 'categorical' },
  { id: '16', name: 'Cookie ID', category: 'Identity & Contact', type: 'categorical' },
  { id: '17', name: 'Social Security Number', category: 'Identity & Contact', type: 'categorical' },
  { id: '18', name: 'Passport Number', category: 'Identity & Contact', type: 'categorical' },
  { id: '19', name: 'Driver License', category: 'Identity & Contact', type: 'categorical' },
  { id: '20', name: 'LinkedIn Profile', category: 'Identity & Contact', type: 'categorical' },
  { id: '21', name: 'Facebook Profile', category: 'Identity & Contact', type: 'categorical' },
  { id: '22', name: 'Twitter Handle', category: 'Identity & Contact', type: 'categorical' },
  { id: '23', name: 'Instagram Handle', category: 'Identity & Contact', type: 'categorical' },
  { id: '24', name: 'TikTok Handle', category: 'Identity & Contact', type: 'categorical' },
  { id: '25', name: 'YouTube Channel', category: 'Identity & Contact', type: 'categorical' },
  { id: '26', name: 'Website URL', category: 'Identity & Contact', type: 'categorical' },
  { id: '27', name: 'Business Email', category: 'Identity & Contact', type: 'categorical' },
  { id: '28', name: 'Personal Email', category: 'Identity & Contact', type: 'categorical' },
  { id: '29', name: 'Alternate Email', category: 'Identity & Contact', type: 'categorical' },
  { id: '30', name: 'Mailing Address', category: 'Identity & Contact', type: 'categorical' },
  { id: '31', name: 'Billing Address', category: 'Identity & Contact', type: 'categorical' },
  { id: '32', name: 'Shipping Address', category: 'Identity & Contact', type: 'categorical' },
  { id: '33', name: 'PO Box', category: 'Identity & Contact', type: 'categorical' },
  { id: '34', name: 'Address Line 2', category: 'Identity & Contact', type: 'categorical' },
  { id: '35', name: 'Address Line 3', category: 'Identity & Contact', type: 'categorical' },
  { id: '36', name: 'County', category: 'Identity & Contact', type: 'categorical' },
  { id: '37', name: 'Metro Area', category: 'Identity & Contact', type: 'categorical' },
  { id: '38', name: 'Time Zone', category: 'Identity & Contact', type: 'categorical' },
  { id: '39', name: 'Area Code', category: 'Identity & Contact', type: 'categorical' },
  { id: '40', name: 'Country Code', category: 'Identity & Contact', type: 'categorical' },
  { id: '41', name: 'Email Domain', category: 'Identity & Contact', type: 'categorical' },
  { id: '42', name: 'Email Provider', category: 'Identity & Contact', type: 'categorical' },
  { id: '43', name: 'Phone Carrier', category: 'Identity & Contact', type: 'categorical' },
  { id: '44', name: 'Phone Type', category: 'Identity & Contact', type: 'categorical' },
  { id: '45', name: 'Address Type', category: 'Identity & Contact', type: 'categorical' },
  { id: '46', name: 'Address Quality Score', category: 'Identity & Contact', type: 'range' },
  { id: '47', name: 'Email Validation Status', category: 'Identity & Contact', type: 'categorical' },
  { id: '48', name: 'Phone Validation Status', category: 'Identity & Contact', type: 'categorical' },
  { id: '49', name: 'Address Validation Status', category: 'Identity & Contact', type: 'categorical' },
  { id: '50', name: 'Identity Score', category: 'Identity & Contact', type: 'range' },
  { id: '51', name: 'Match Confidence', category: 'Identity & Contact', type: 'range' },
  { id: '52', name: 'Data Source', category: 'Identity & Contact', type: 'categorical' },
  { id: '53', name: 'Data Freshness', category: 'Identity & Contact', type: 'categorical' },
  { id: '54', name: 'Last Updated', category: 'Identity & Contact', type: 'categorical' },
  { id: '55', name: 'Verification Date', category: 'Identity & Contact', type: 'categorical' },
  { id: '56', name: 'Opt-Out Status', category: 'Identity & Contact', type: 'categorical' },
  { id: '57', name: 'Do Not Call', category: 'Identity & Contact', type: 'categorical' },
  { id: '58', name: 'Do Not Email', category: 'Identity & Contact', type: 'categorical' },
  { id: '59', name: 'Do Not Mail', category: 'Identity & Contact', type: 'categorical' },
  { id: '60', name: 'Privacy Preference', category: 'Identity & Contact', type: 'categorical' },
  { id: '61', name: 'GDPR Consent', category: 'Identity & Contact', type: 'categorical' },
  { id: '62', name: 'CCPA Consent', category: 'Identity & Contact', type: 'categorical' },
  { id: '63', name: 'CAN-SPAM Status', category: 'Identity & Contact', type: 'categorical' },
  { id: '64', name: 'TCPA Status', category: 'Identity & Contact', type: 'categorical' },
  { id: '65', name: 'Data Quality Score', category: 'Identity & Contact', type: 'range' },
  { id: '66', name: 'Completeness Score', category: 'Identity & Contact', type: 'range' },
  { id: '67', name: 'Accuracy Score', category: 'Identity & Contact', type: 'range' },
  { id: '68', name: 'Recency Score', category: 'Identity & Contact', type: 'range' },
  { id: '69', name: 'Verification Method', category: 'Identity & Contact', type: 'categorical' },
  { id: '70', name: 'Verification Level', category: 'Identity & Contact', type: 'categorical' },
  { id: '71', name: 'Identity Graph ID', category: 'Identity & Contact', type: 'categorical' },
  { id: '72', name: 'Household ID', category: 'Identity & Contact', type: 'categorical' },
  { id: '73', name: 'Person ID', category: 'Identity & Contact', type: 'categorical' },
  { id: '74', name: 'Device Fingerprint', category: 'Identity & Contact', type: 'categorical' },
  { id: '75', name: 'Browser Fingerprint', category: 'Identity & Contact', type: 'categorical' },
  { id: '76', name: 'Mobile Device ID', category: 'Identity & Contact', type: 'categorical' },
  { id: '77', name: 'Tablet Device ID', category: 'Identity & Contact', type: 'categorical' },
  { id: '78', name: 'Desktop Device ID', category: 'Identity & Contact', type: 'categorical' },
  { id: '79', name: 'Cross-Device ID', category: 'Identity & Contact', type: 'categorical' },
  { id: '80', name: 'Universal ID', category: 'Identity & Contact', type: 'categorical' },

  // Demographics (100 attributes)
  { id: '81', name: 'Age', category: 'Demographics', type: 'range' },
  { id: '82', name: 'Gender', category: 'Demographics', type: 'categorical' },
  { id: '83', name: 'Date of Birth', category: 'Demographics', type: 'categorical' },
  { id: '84', name: 'Birth Year', category: 'Demographics', type: 'range' },
  { id: '85', name: 'Birth Month', category: 'Demographics', type: 'categorical' },
  { id: '86', name: 'Birth Day', category: 'Demographics', type: 'range' },
  { id: '87', name: 'Age Range', category: 'Demographics', type: 'categorical' },
  { id: '88', name: 'Generation', category: 'Demographics', type: 'categorical' },
  { id: '89', name: 'Marital Status', category: 'Demographics', type: 'categorical' },
  { id: '90', name: 'Marriage Date', category: 'Demographics', type: 'categorical' },
  { id: '91', name: 'Divorce Date', category: 'Demographics', type: 'categorical' },
  { id: '92', name: 'Spouse Name', category: 'Demographics', type: 'categorical' },
  { id: '93', name: 'Number of Children', category: 'Demographics', type: 'range' },
  { id: '94', name: 'Children Ages', category: 'Demographics', type: 'categorical' },
  { id: '95', name: 'Household Size', category: 'Demographics', type: 'range' },
  { id: '96', name: 'Ethnicity', category: 'Demographics', type: 'categorical' },
  { id: '97', name: 'Race', category: 'Demographics', type: 'categorical' },
  { id: '98', name: 'Religion', category: 'Demographics', type: 'categorical' },
  { id: '99', name: 'Language', category: 'Demographics', type: 'categorical' },
  { id: '100', name: 'Primary Language', category: 'Demographics', type: 'categorical' },
  { id: '101', name: 'Secondary Language', category: 'Demographics', type: 'categorical' },
  { id: '102', name: 'Nationality', category: 'Demographics', type: 'categorical' },
  { id: '103', name: 'Country of Origin', category: 'Demographics', type: 'categorical' },
  { id: '104', name: 'Citizenship Status', category: 'Demographics', type: 'categorical' },
  { id: '105', name: 'Veteran Status', category: 'Demographics', type: 'categorical' },
  { id: '106', name: 'Disability Status', category: 'Demographics', type: 'categorical' },
  { id: '107', name: 'Education Level', category: 'Demographics', type: 'categorical' },
  { id: '108', name: 'Highest Degree', category: 'Demographics', type: 'categorical' },
  { id: '109', name: 'School Name', category: 'Demographics', type: 'categorical' },
  { id: '110', name: 'Graduation Year', category: 'Demographics', type: 'range' },
  { id: '111', name: 'Field of Study', category: 'Demographics', type: 'categorical' },
  { id: '112', name: 'Major', category: 'Demographics', type: 'categorical' },
  { id: '113', name: 'Minor', category: 'Demographics', type: 'categorical' },
  { id: '114', name: 'GPA', category: 'Demographics', type: 'range' },
  { id: '115', name: 'Honors', category: 'Demographics', type: 'categorical' },
  { id: '116', name: 'Alumni Status', category: 'Demographics', type: 'categorical' },
  { id: '117', name: 'Fraternity/Sorority', category: 'Demographics', type: 'categorical' },
  { id: '118', name: 'Political Affiliation', category: 'Demographics', type: 'categorical' },
  { id: '119', name: 'Voting Record', category: 'Demographics', type: 'categorical' },
  { id: '120', name: 'Voter Registration', category: 'Demographics', type: 'categorical' },
  { id: '121', name: 'Party Registration', category: 'Demographics', type: 'categorical' },
  { id: '122', name: 'Voting Frequency', category: 'Demographics', type: 'categorical' },
  { id: '123', name: 'Primary Voting Method', category: 'Demographics', type: 'categorical' },
  { id: '124', name: 'Life Stage', category: 'Demographics', type: 'categorical' },
  { id: '125', name: 'Life Events', category: 'Demographics', type: 'categorical' },
  { id: '126', name: 'Recent Life Event', category: 'Demographics', type: 'categorical' },
  { id: '127', name: 'Family Structure', category: 'Demographics', type: 'categorical' },
  { id: '128', name: 'Parental Status', category: 'Demographics', type: 'categorical' },
  { id: '129', name: 'Grandparent Status', category: 'Demographics', type: 'categorical' },
  { id: '130', name: 'Pet Owner', category: 'Demographics', type: 'categorical' },
  { id: '131', name: 'Pet Type', category: 'Demographics', type: 'categorical' },
  { id: '132', name: 'Number of Pets', category: 'Demographics', type: 'range' },
  { id: '133', name: 'Health Conditions', category: 'Demographics', type: 'categorical' },
  { id: '134', name: 'Medical Conditions', category: 'Demographics', type: 'categorical' },
  { id: '135', name: 'Prescription Medications', category: 'Demographics', type: 'categorical' },
  { id: '136', name: 'Health Insurance', category: 'Demographics', type: 'categorical' },
  { id: '137', name: 'Insurance Provider', category: 'Demographics', type: 'categorical' },
  { id: '138', name: 'Blood Type', category: 'Demographics', type: 'categorical' },
  { id: '139', name: 'Organ Donor', category: 'Demographics', type: 'categorical' },
  { id: '140', name: 'Height', category: 'Demographics', type: 'range' },
  { id: '141', name: 'Weight', category: 'Demographics', type: 'range' },
  { id: '142', name: 'BMI', category: 'Demographics', type: 'range' },
  { id: '143', name: 'Body Type', category: 'Demographics', type: 'categorical' },
  { id: '144', name: 'Hair Color', category: 'Demographics', type: 'categorical' },
  { id: '145', name: 'Eye Color', category: 'Demographics', type: 'categorical' },
  { id: '146', name: 'Skin Tone', category: 'Demographics', type: 'categorical' },
  { id: '147', name: 'Fitness Level', category: 'Demographics', type: 'categorical' },
  { id: '148', name: 'Exercise Frequency', category: 'Demographics', type: 'categorical' },
  { id: '149', name: 'Diet Type', category: 'Demographics', type: 'categorical' },
  { id: '150', name: 'Smoking Status', category: 'Demographics', type: 'categorical' },
  { id: '151', name: 'Alcohol Consumption', category: 'Demographics', type: 'categorical' },
  { id: '152', name: 'Caffeine Consumption', category: 'Demographics', type: 'categorical' },
  { id: '153', name: 'Sleep Patterns', category: 'Demographics', type: 'categorical' },
  { id: '154', name: 'Stress Level', category: 'Demographics', type: 'range' },
  { id: '155', name: 'Mental Health', category: 'Demographics', type: 'categorical' },
  { id: '156', name: 'Anxiety Level', category: 'Demographics', type: 'range' },
  { id: '157', name: 'Depression Level', category: 'Demographics', type: 'range' },
  { id: '158', name: 'Happiness Index', category: 'Demographics', type: 'range' },
  { id: '159', name: 'Life Satisfaction', category: 'Demographics', type: 'range' },
  { id: '160', name: 'Social Media Usage', category: 'Demographics', type: 'categorical' },
  { id: '161', name: 'Social Media Platforms', category: 'Demographics', type: 'categorical' },
  { id: '162', name: 'Online Activity Level', category: 'Demographics', type: 'categorical' },
  { id: '163', name: 'Digital Literacy', category: 'Demographics', type: 'categorical' },
  { id: '164', name: 'Technology Adoption', category: 'Demographics', type: 'categorical' },
  { id: '165', name: 'Mobile Usage', category: 'Demographics', type: 'categorical' },
  { id: '166', name: 'Desktop Usage', category: 'Demographics', type: 'categorical' },
  { id: '167', name: 'Tablet Usage', category: 'Demographics', type: 'categorical' },
  { id: '168', name: 'Gaming Interest', category: 'Demographics', type: 'categorical' },
  { id: '169', name: 'Gaming Frequency', category: 'Demographics', type: 'categorical' },
  { id: '170', name: 'Gaming Platforms', category: 'Demographics', type: 'categorical' },
  { id: '171', name: 'Streaming Services', category: 'Demographics', type: 'categorical' },
  { id: '172', name: 'Music Preferences', category: 'Demographics', type: 'categorical' },
  { id: '173', name: 'Movie Preferences', category: 'Demographics', type: 'categorical' },
  { id: '174', name: 'TV Show Preferences', category: 'Demographics', type: 'categorical' },
  { id: '175', name: 'Book Preferences', category: 'Demographics', type: 'categorical' },
  { id: '176', name: 'Magazine Preferences', category: 'Demographics', type: 'categorical' },
  { id: '177', name: 'Newspaper Preferences', category: 'Demographics', type: 'categorical' },
  { id: '178', name: 'Radio Preferences', category: 'Demographics', type: 'categorical' },
  { id: '179', name: 'Podcast Preferences', category: 'Demographics', type: 'categorical' },
  { id: '180', name: 'Hobbies', category: 'Demographics', type: 'categorical' },

  // Financial & Wealth (120 attributes)
  { id: '181', name: 'Income Range', category: 'Financial & Wealth', type: 'range' },
  { id: '182', name: 'Annual Income', category: 'Financial & Wealth', type: 'range' },
  { id: '183', name: 'Monthly Income', category: 'Financial & Wealth', type: 'range' },
  { id: '184', name: 'Household Income', category: 'Financial & Wealth', type: 'range' },
  { id: '185', name: 'Disposable Income', category: 'Financial & Wealth', type: 'range' },
  { id: '186', name: 'Net Worth', category: 'Financial & Wealth', type: 'range' },
  { id: '187', name: 'Liquid Assets', category: 'Financial & Wealth', type: 'range' },
  { id: '188', name: 'Investment Assets', category: 'Financial & Wealth', type: 'range' },
  { id: '189', name: 'Retirement Assets', category: 'Financial & Wealth', type: 'range' },
  { id: '190', name: 'Real Estate Value', category: 'Financial & Wealth', type: 'range' },
  { id: '191', name: 'Vehicle Value', category: 'Financial & Wealth', type: 'range' },
  { id: '192', name: 'Total Assets', category: 'Financial & Wealth', type: 'range' },
  { id: '193', name: 'Total Liabilities', category: 'Financial & Wealth', type: 'range' },
  { id: '194', name: 'Debt Amount', category: 'Financial & Wealth', type: 'range' },
  { id: '195', name: 'Credit Card Debt', category: 'Financial & Wealth', type: 'range' },
  { id: '196', name: 'Mortgage Debt', category: 'Financial & Wealth', type: 'range' },
  { id: '197', name: 'Auto Loan Debt', category: 'Financial & Wealth', type: 'range' },
  { id: '198', name: 'Student Loan Debt', category: 'Financial & Wealth', type: 'range' },
  { id: '199', name: 'Personal Loan Debt', category: 'Financial & Wealth', type: 'range' },
  { id: '200', name: 'Credit Score', category: 'Financial & Wealth', type: 'range' },
  { id: '201', name: 'Credit Score Range', category: 'Financial & Wealth', type: 'categorical' },
  { id: '202', name: 'Credit Rating', category: 'Financial & Wealth', type: 'categorical' },
  { id: '203', name: 'Credit Bureau', category: 'Financial & Wealth', type: 'categorical' },
  { id: '204', name: 'Credit History Length', category: 'Financial & Wealth', type: 'range' },
  { id: '205', name: 'Number of Credit Cards', category: 'Financial & Wealth', type: 'range' },
  { id: '206', name: 'Credit Card Type', category: 'Financial & Wealth', type: 'categorical' },
  { id: '207', name: 'Credit Card Brand', category: 'Financial & Wealth', type: 'categorical' },
  { id: '208', name: 'Credit Card Limit', category: 'Financial & Wealth', type: 'range' },
  { id: '209', name: 'Credit Utilization', category: 'Financial & Wealth', type: 'range' },
  { id: '210', name: 'Payment History', category: 'Financial & Wealth', type: 'categorical' },
  { id: '211', name: 'Late Payments', category: 'Financial & Wealth', type: 'range' },
  { id: '212', name: 'Bankruptcies', category: 'Financial & Wealth', type: 'range' },
  { id: '213', name: 'Foreclosures', category: 'Financial & Wealth', type: 'range' },
  { id: '214', name: 'Collections', category: 'Financial & Wealth', type: 'range' },
  { id: '215', name: 'Tax Liens', category: 'Financial & Wealth', type: 'range' },
  { id: '216', name: 'Judgments', category: 'Financial & Wealth', type: 'range' },
  { id: '217', name: 'Bank Account Type', category: 'Financial & Wealth', type: 'categorical' },
  { id: '218', name: 'Bank Name', category: 'Financial & Wealth', type: 'categorical' },
  { id: '219', name: 'Number of Bank Accounts', category: 'Financial & Wealth', type: 'range' },
  { id: '220', name: 'Checking Account', category: 'Financial & Wealth', type: 'categorical' },
  { id: '221', name: 'Savings Account', category: 'Financial & Wealth', type: 'categorical' },
  { id: '222', name: 'Money Market Account', category: 'Financial & Wealth', type: 'categorical' },
  { id: '223', name: 'CD Account', category: 'Financial & Wealth', type: 'categorical' },
  { id: '224', name: 'IRA Account', category: 'Financial & Wealth', type: 'categorical' },
  { id: '225', name: '401k Account', category: 'Financial & Wealth', type: 'categorical' },
  { id: '226', name: 'Roth IRA', category: 'Financial & Wealth', type: 'categorical' },
  { id: '227', name: 'Pension', category: 'Financial & Wealth', type: 'categorical' },
  { id: '228', name: 'Annuity', category: 'Financial & Wealth', type: 'categorical' },
  { id: '229', name: 'Investment Account', category: 'Financial & Wealth', type: 'categorical' },
  { id: '230', name: 'Brokerage Account', category: 'Financial & Wealth', type: 'categorical' },
  { id: '231', name: 'Stock Holdings', category: 'Financial & Wealth', type: 'categorical' },
  { id: '232', name: 'Bond Holdings', category: 'Financial & Wealth', type: 'categorical' },
  { id: '233', name: 'Mutual Fund Holdings', category: 'Financial & Wealth', type: 'categorical' },
  { id: '234', name: 'ETF Holdings', category: 'Financial & Wealth', type: 'categorical' },
  { id: '235', name: 'Options Holdings', category: 'Financial & Wealth', type: 'categorical' },
  { id: '236', name: 'Cryptocurrency Holdings', category: 'Financial & Wealth', type: 'categorical' },
  { id: '237', name: 'Crypto Amount', category: 'Financial & Wealth', type: 'range' },
  { id: '238', name: 'Insurance Policies', category: 'Financial & Wealth', type: 'categorical' },
  { id: '239', name: 'Life Insurance', category: 'Financial & Wealth', type: 'categorical' },
  { id: '240', name: 'Life Insurance Amount', category: 'Financial & Wealth', type: 'range' },
  { id: '241', name: 'Health Insurance', category: 'Financial & Wealth', type: 'categorical' },
  { id: '242', name: 'Auto Insurance', category: 'Financial & Wealth', type: 'categorical' },
  { id: '243', name: 'Home Insurance', category: 'Financial & Wealth', type: 'categorical' },
  { id: '244', name: 'Renters Insurance', category: 'Financial & Wealth', type: 'categorical' },
  { id: '245', name: 'Disability Insurance', category: 'Financial & Wealth', type: 'categorical' },
  { id: '246', name: 'Long Term Care Insurance', category: 'Financial & Wealth', type: 'categorical' },
  { id: '247', name: 'Umbrella Insurance', category: 'Financial & Wealth', type: 'categorical' },
  { id: '248', name: 'Travel Insurance', category: 'Financial & Wealth', type: 'categorical' },
  { id: '249', name: 'Pet Insurance', category: 'Financial & Wealth', type: 'categorical' },
  { id: '250', name: 'Financial Advisor', category: 'Financial & Wealth', type: 'categorical' },
  { id: '251', name: 'Financial Planning', category: 'Financial & Wealth', type: 'categorical' },
  { id: '252', name: 'Estate Planning', category: 'Financial & Wealth', type: 'categorical' },
  { id: '253', name: 'Tax Preparation', category: 'Financial & Wealth', type: 'categorical' },
  { id: '254', name: 'Tax Filing Status', category: 'Financial & Wealth', type: 'categorical' },
  { id: '255', name: 'Tax Bracket', category: 'Financial & Wealth', type: 'categorical' },
  { id: '256', name: 'Tax Refund', category: 'Financial & Wealth', type: 'range' },
  { id: '257', name: 'Charitable Giving', category: 'Financial & Wealth', type: 'categorical' },
  { id: '258', name: 'Charitable Donations', category: 'Financial & Wealth', type: 'range' },
  { id: '259', name: 'Donation Frequency', category: 'Financial & Wealth', type: 'categorical' },
  { id: '260', name: 'Causes Supported', category: 'Financial & Wealth', type: 'categorical' },
  { id: '261', name: 'Payment Methods', category: 'Financial & Wealth', type: 'categorical' },
  { id: '262', name: 'Credit Card Usage', category: 'Financial & Wealth', type: 'categorical' },
  { id: '263', name: 'Debit Card Usage', category: 'Financial & Wealth', type: 'categorical' },
  { id: '264', name: 'Cash Usage', category: 'Financial & Wealth', type: 'categorical' },
  { id: '265', name: 'Digital Wallet', category: 'Financial & Wealth', type: 'categorical' },
  { id: '266', name: 'Mobile Payment', category: 'Financial & Wealth', type: 'categorical' },
  { id: '267', name: 'Cryptocurrency Usage', category: 'Financial & Wealth', type: 'categorical' },
  { id: '268', name: 'Online Banking', category: 'Financial & Wealth', type: 'categorical' },
  { id: '269', name: 'Mobile Banking', category: 'Financial & Wealth', type: 'categorical' },
  { id: '270', name: 'Bill Pay Service', category: 'Financial & Wealth', type: 'categorical' },
  { id: '271', name: 'Auto Pay', category: 'Financial & Wealth', type: 'categorical' },
  { id: '272', name: 'Subscription Services', category: 'Financial & Wealth', type: 'categorical' },
  { id: '273', name: 'Subscription Count', category: 'Financial & Wealth', type: 'range' },
  { id: '274', name: 'Monthly Subscription Spend', category: 'Financial & Wealth', type: 'range' },
  { id: '275', name: 'Streaming Subscriptions', category: 'Financial & Wealth', type: 'categorical' },
  { id: '276', name: 'Gaming Subscriptions', category: 'Financial & Wealth', type: 'categorical' },
  { id: '277', name: 'Software Subscriptions', category: 'Financial & Wealth', type: 'categorical' },
  { id: '278', name: 'Cloud Storage', category: 'Financial & Wealth', type: 'categorical' },
  { id: '279', name: 'Music Subscriptions', category: 'Financial & Wealth', type: 'categorical' },
  { id: '280', name: 'News Subscriptions', category: 'Financial & Wealth', type: 'categorical' },
  { id: '281', name: 'Magazine Subscriptions', category: 'Financial & Wealth', type: 'categorical' },
  { id: '282', name: 'Meal Kit Subscriptions', category: 'Financial & Wealth', type: 'categorical' },
  { id: '283', name: 'Box Subscriptions', category: 'Financial & Wealth', type: 'categorical' },
  { id: '284', name: 'Fitness Subscriptions', category: 'Financial & Wealth', type: 'categorical' },
  { id: '285', name: 'Education Subscriptions', category: 'Financial & Wealth', type: 'categorical' },
  { id: '286', name: 'Shopping Habits', category: 'Financial & Wealth', type: 'categorical' },
  { id: '287', name: 'Online Shopping Frequency', category: 'Financial & Wealth', type: 'categorical' },
  { id: '288', name: 'In-Store Shopping Frequency', category: 'Financial & Wealth', type: 'categorical' },
  { id: '289', name: 'Average Order Value', category: 'Financial & Wealth', type: 'range' },
  { id: '290', name: 'Annual Shopping Spend', category: 'Financial & Wealth', type: 'range' },
  { id: '291', name: 'Retailer Preferences', category: 'Financial & Wealth', type: 'categorical' },
  { id: '292', name: 'Brand Preferences', category: 'Financial & Wealth', type: 'categorical' },
  { id: '293', name: 'Luxury Brand Affinity', category: 'Financial & Wealth', type: 'categorical' },
  { id: '294', name: 'Discount Shopping', category: 'Financial & Wealth', type: 'categorical' },
  { id: '295', name: 'Coupon Usage', category: 'Financial & Wealth', type: 'categorical' },
  { id: '296', name: 'Rewards Program Participation', category: 'Financial & Wealth', type: 'categorical' },
  { id: '297', name: 'Loyalty Program Membership', category: 'Financial & Wealth', type: 'categorical' },
  { id: '298', name: 'Cashback Programs', category: 'Financial & Wealth', type: 'categorical' },
  { id: '299', name: 'Points Programs', category: 'Financial & Wealth', type: 'categorical' },
  { id: '300', name: 'Miles Programs', category: 'Financial & Wealth', type: 'categorical' },

  // Home & Property (100 attributes)
  { id: '301', name: 'Home Owner Status', category: 'Home & Property', type: 'categorical' },
  { id: '302', name: 'Property Type', category: 'Home & Property', type: 'categorical' },
  { id: '303', name: 'Property Value', category: 'Home & Property', type: 'range' },
  { id: '304', name: 'Home Purchase Price', category: 'Home & Property', type: 'range' },
  { id: '305', name: 'Home Purchase Date', category: 'Home & Property', type: 'categorical' },
  { id: '306', name: 'Years Owned', category: 'Home & Property', type: 'range' },
  { id: '307', name: 'Mortgage Amount', category: 'Home & Property', type: 'range' },
  { id: '308', name: 'Mortgage Rate', category: 'Home & Property', type: 'range' },
  { id: '309', name: 'Mortgage Term', category: 'Home & Property', type: 'range' },
  { id: '310', name: 'Mortgage Lender', category: 'Home & Property', type: 'categorical' },
  { id: '311', name: 'Mortgage Type', category: 'Home & Property', type: 'categorical' },
  { id: '312', name: 'Home Equity', category: 'Home & Property', type: 'range' },
  { id: '313', name: 'Home Equity Line of Credit', category: 'Home & Property', type: 'categorical' },
  { id: '314', name: 'HELOC Amount', category: 'Home & Property', type: 'range' },
  { id: '315', name: 'Property Tax', category: 'Home & Property', type: 'range' },
  { id: '316', name: 'Home Insurance', category: 'Home & Property', type: 'categorical' },
  { id: '317', name: 'Home Insurance Amount', category: 'Home & Property', type: 'range' },
  { id: '318', name: 'Square Footage', category: 'Home & Property', type: 'range' },
  { id: '319', name: 'Lot Size', category: 'Home & Property', type: 'range' },
  { id: '320', name: 'Number of Bedrooms', category: 'Home & Property', type: 'range' },
  { id: '321', name: 'Number of Bathrooms', category: 'Home & Property', type: 'range' },
  { id: '322', name: 'Number of Stories', category: 'Home & Property', type: 'range' },
  { id: '323', name: 'Year Built', category: 'Home & Property', type: 'range' },
  { id: '324', name: 'Year Renovated', category: 'Home & Property', type: 'range' },
  { id: '325', name: 'Home Age', category: 'Home & Property', type: 'range' },
  { id: '326', name: 'Home Condition', category: 'Home & Property', type: 'categorical' },
  { id: '327', name: 'Home Style', category: 'Home & Property', type: 'categorical' },
  { id: '328', name: 'Architectural Style', category: 'Home & Property', type: 'categorical' },
  { id: '329', name: 'Roof Type', category: 'Home & Property', type: 'categorical' },
  { id: '330', name: 'Exterior Material', category: 'Home & Property', type: 'categorical' },
  { id: '331', name: 'Foundation Type', category: 'Home & Property', type: 'categorical' },
  { id: '332', name: 'Heating Type', category: 'Home & Property', type: 'categorical' },
  { id: '333', name: 'Cooling Type', category: 'Home & Property', type: 'categorical' },
  { id: '334', name: 'Energy Efficiency', category: 'Home & Property', type: 'categorical' },
  { id: '335', name: 'Solar Panels', category: 'Home & Property', type: 'categorical' },
  { id: '336', name: 'Garage', category: 'Home & Property', type: 'categorical' },
  { id: '337', name: 'Garage Size', category: 'Home & Property', type: 'range' },
  { id: '338', name: 'Parking Spaces', category: 'Home & Property', type: 'range' },
  { id: '339', name: 'Basement', category: 'Home & Property', type: 'categorical' },
  { id: '340', name: 'Basement Type', category: 'Home & Property', type: 'categorical' },
  { id: '341', name: 'Attic', category: 'Home & Property', type: 'categorical' },
  { id: '342', name: 'Fireplace', category: 'Home & Property', type: 'categorical' },
  { id: '343', name: 'Number of Fireplaces', category: 'Home & Property', type: 'range' },
  { id: '344', name: 'Pool', category: 'Home & Property', type: 'categorical' },
  { id: '345', name: 'Pool Type', category: 'Home & Property', type: 'categorical' },
  { id: '346', name: 'Spa', category: 'Home & Property', type: 'categorical' },
  { id: '347', name: 'Hot Tub', category: 'Home & Property', type: 'categorical' },
  { id: '348', name: 'Deck', category: 'Home & Property', type: 'categorical' },
  { id: '349', name: 'Patio', category: 'Home & Property', type: 'categorical' },
  { id: '350', name: 'Porch', category: 'Home & Property', type: 'categorical' },
  { id: '351', name: 'Balcony', category: 'Home & Property', type: 'categorical' },
  { id: '352', name: 'Fence', category: 'Home & Property', type: 'categorical' },
  { id: '353', name: 'Fence Type', category: 'Home & Property', type: 'categorical' },
  { id: '354', name: 'Yard Size', category: 'Home & Property', type: 'categorical' },
  { id: '355', name: 'Landscaping', category: 'Home & Property', type: 'categorical' },
  { id: '356', name: 'Garden', category: 'Home & Property', type: 'categorical' },
  { id: '357', name: 'Outdoor Kitchen', category: 'Home & Property', type: 'categorical' },
  { id: '358', name: 'Outdoor Living Space', category: 'Home & Property', type: 'categorical' },
  { id: '359', name: 'Home Security System', category: 'Home & Property', type: 'categorical' },
  { id: '360', name: 'Security System Type', category: 'Home & Property', type: 'categorical' },
  { id: '361', name: 'Smart Home Features', category: 'Home & Property', type: 'categorical' },
  { id: '362', name: 'Smart Thermostat', category: 'Home & Property', type: 'categorical' },
  { id: '363', name: 'Smart Lighting', category: 'Home & Property', type: 'categorical' },
  { id: '364', name: 'Smart Locks', category: 'Home & Property', type: 'categorical' },
  { id: '365', name: 'Smart Cameras', category: 'Home & Property', type: 'categorical' },
  { id: '366', name: 'Smart Speakers', category: 'Home & Property', type: 'categorical' },
  { id: '367', name: 'Voice Assistant', category: 'Home & Property', type: 'categorical' },
  { id: '368', name: 'Home Automation', category: 'Home & Property', type: 'categorical' },
  { id: '369', name: 'Home Theater', category: 'Home & Property', type: 'categorical' },
  { id: '370', name: 'Wine Cellar', category: 'Home & Property', type: 'categorical' },
  { id: '371', name: 'Home Gym', category: 'Home & Property', type: 'categorical' },
  { id: '372', name: 'Home Office', category: 'Home & Property', type: 'categorical' },
  { id: '373', name: 'Home Library', category: 'Home & Property', type: 'categorical' },
  { id: '374', name: 'Workshop', category: 'Home & Property', type: 'categorical' },
  { id: '375', name: 'Mud Room', category: 'Home & Property', type: 'categorical' },
  { id: '376', name: 'Laundry Room', category: 'Home & Property', type: 'categorical' },
  { id: '377', name: 'Walk-in Closet', category: 'Home & Property', type: 'categorical' },
  { id: '378', name: 'Master Suite', category: 'Home & Property', type: 'categorical' },
  { id: '379', name: 'Guest Room', category: 'Home & Property', type: 'categorical' },
  { id: '380', name: 'Number of Guest Rooms', category: 'Home & Property', type: 'range' },
  { id: '381', name: 'Dining Room', category: 'Home & Property', type: 'categorical' },
  { id: '382', name: 'Formal Dining Room', category: 'Home & Property', type: 'categorical' },
  { id: '383', name: 'Breakfast Nook', category: 'Home & Property', type: 'categorical' },
  { id: '384', name: 'Kitchen Island', category: 'Home & Property', type: 'categorical' },
  { id: '385', name: 'Granite Countertops', category: 'Home & Property', type: 'categorical' },
  { id: '386', name: 'Stainless Steel Appliances', category: 'Home & Property', type: 'categorical' },
  { id: '387', name: 'Updated Kitchen', category: 'Home & Property', type: 'categorical' },
  { id: '388', name: 'Updated Bathroom', category: 'Home & Property', type: 'categorical' },
  { id: '389', name: 'Hardwood Floors', category: 'Home & Property', type: 'categorical' },
  { id: '390', name: 'Carpet', category: 'Home & Property', type: 'categorical' },
  { id: '391', name: 'Tile Floors', category: 'Home & Property', type: 'categorical' },
  { id: '392', name: 'Laminate Floors', category: 'Home & Property', type: 'categorical' },
  { id: '393', name: 'Vinyl Floors', category: 'Home & Property', type: 'categorical' },
  { id: '394', name: 'Crown Molding', category: 'Home & Property', type: 'categorical' },
  { id: '395', name: 'Wainscoting', category: 'Home & Property', type: 'categorical' },
  { id: '396', name: 'Bay Windows', category: 'Home & Property', type: 'categorical' },
  { id: '397', name: 'Skylights', category: 'Home & Property', type: 'categorical' },
  { id: '398', name: 'Ceiling Fans', category: 'Home & Property', type: 'categorical' },
  { id: '399', name: 'Recessed Lighting', category: 'Home & Property', type: 'categorical' },
  { id: '400', name: 'Chandelier', category: 'Home & Property', type: 'categorical' },

  // Professional (80 attributes)
  { id: '401', name: 'Job Title', category: 'Professional', type: 'categorical' },
  { id: '402', name: 'Job Function', category: 'Professional', type: 'categorical' },
  { id: '403', name: 'Industry', category: 'Professional', type: 'categorical' },
  { id: '404', name: 'Company Name', category: 'Professional', type: 'categorical' },
  { id: '405', name: 'Company Size', category: 'Professional', type: 'categorical' },
  { id: '406', name: 'Company Revenue', category: 'Professional', type: 'range' },
  { id: '407', name: 'Company Type', category: 'Professional', type: 'categorical' },
  { id: '408', name: 'Department', category: 'Professional', type: 'categorical' },
  { id: '409', name: 'Management Level', category: 'Professional', type: 'categorical' },
  { id: '410', name: 'Seniority Level', category: 'Professional', type: 'categorical' },
  { id: '411', name: 'Years of Experience', category: 'Professional', type: 'range' },
  { id: '412', name: 'Years at Company', category: 'Professional', type: 'range' },
  { id: '413', name: 'Employment Status', category: 'Professional', type: 'categorical' },
  { id: '414', name: 'Employment Type', category: 'Professional', type: 'categorical' },
  { id: '415', name: 'Work Location', category: 'Professional', type: 'categorical' },
  { id: '416', name: 'Remote Work', category: 'Professional', type: 'categorical' },
  { id: '417', name: 'Hybrid Work', category: 'Professional', type: 'categorical' },
  { id: '418', name: 'Work From Home', category: 'Professional', type: 'categorical' },
  { id: '419', name: 'Office Location', category: 'Professional', type: 'categorical' },
  { id: '420', name: 'Work Address', category: 'Professional', type: 'categorical' },
  { id: '421', name: 'Work City', category: 'Professional', type: 'categorical' },
  { id: '422', name: 'Work State', category: 'Professional', type: 'categorical' },
  { id: '423', name: 'Work ZIP', category: 'Professional', type: 'categorical' },
  { id: '424', name: 'Work Country', category: 'Professional', type: 'categorical' },
  { id: '425', name: 'Salary Range', category: 'Professional', type: 'range' },
  { id: '426', name: 'Annual Salary', category: 'Professional', type: 'range' },
  { id: '427', name: 'Hourly Wage', category: 'Professional', type: 'range' },
  { id: '428', name: 'Bonus', category: 'Professional', type: 'range' },
  { id: '429', name: 'Commission', category: 'Professional', type: 'range' },
  { id: '430', name: 'Total Compensation', category: 'Professional', type: 'range' },
  { id: '431', name: 'Benefits Package', category: 'Professional', type: 'categorical' },
  { id: '432', name: 'Health Insurance', category: 'Professional', type: 'categorical' },
  { id: '433', name: 'Dental Insurance', category: 'Professional', type: 'categorical' },
  { id: '434', name: 'Vision Insurance', category: 'Professional', type: 'categorical' },
  { id: '435', name: '401k Match', category: 'Professional', type: 'categorical' },
  { id: '436', name: 'Stock Options', category: 'Professional', type: 'categorical' },
  { id: '437', name: 'Equity', category: 'Professional', type: 'categorical' },
  { id: '438', name: 'Paid Time Off', category: 'Professional', type: 'range' },
  { id: '439', name: 'Sick Days', category: 'Professional', type: 'range' },
  { id: '440', name: 'Vacation Days', category: 'Professional', type: 'range' },
  { id: '441', name: 'Flexible Hours', category: 'Professional', type: 'categorical' },
  { id: '442', name: 'Compressed Workweek', category: 'Professional', type: 'categorical' },
  { id: '443', name: 'Job Sharing', category: 'Professional', type: 'categorical' },
  { id: '444', name: 'Part-Time', category: 'Professional', type: 'categorical' },
  { id: '445', name: 'Full-Time', category: 'Professional', type: 'categorical' },
  { id: '446', name: 'Contract', category: 'Professional', type: 'categorical' },
  { id: '447', name: 'Temporary', category: 'Professional', type: 'categorical' },
  { id: '448', name: 'Internship', category: 'Professional', type: 'categorical' },
  { id: '449', name: 'Freelance', category: 'Professional', type: 'categorical' },
  { id: '450', name: 'Consultant', category: 'Professional', type: 'categorical' },
  { id: '451', name: 'Self-Employed', category: 'Professional', type: 'categorical' },
  { id: '452', name: 'Entrepreneur', category: 'Professional', type: 'categorical' },
  { id: '453', name: 'Business Owner', category: 'Professional', type: 'categorical' },
  { id: '454', name: 'Board Member', category: 'Professional', type: 'categorical' },
  { id: '455', name: 'Advisor', category: 'Professional', type: 'categorical' },
  { id: '456', name: 'Investor', category: 'Professional', type: 'categorical' },
  { id: '457', name: 'Angel Investor', category: 'Professional', type: 'categorical' },
  { id: '458', name: 'Venture Capitalist', category: 'Professional', type: 'categorical' },
  { id: '459', name: 'Skills', category: 'Professional', type: 'categorical' },
  { id: '460', name: 'Technical Skills', category: 'Professional', type: 'categorical' },
  { id: '461', name: 'Soft Skills', category: 'Professional', type: 'categorical' },
  { id: '462', name: 'Certifications', category: 'Professional', type: 'categorical' },
  { id: '463', name: 'Licenses', category: 'Professional', type: 'categorical' },
  { id: '464', name: 'Professional Associations', category: 'Professional', type: 'categorical' },
  { id: '465', name: 'Industry Associations', category: 'Professional', type: 'categorical' },
  { id: '466', name: 'Awards', category: 'Professional', type: 'categorical' },
  { id: '467', name: 'Publications', category: 'Professional', type: 'categorical' },
  { id: '468', name: 'Patents', category: 'Professional', type: 'categorical' },
  { id: '469', name: 'Speaking Engagements', category: 'Professional', type: 'categorical' },
  { id: '470', name: 'Conference Attendance', category: 'Professional', type: 'categorical' },
  { id: '471', name: 'Training Programs', category: 'Professional', type: 'categorical' },
  { id: '472', name: 'Continuing Education', category: 'Professional', type: 'categorical' },
  { id: '473', name: 'Professional Development', category: 'Professional', type: 'categorical' },
  { id: '474', name: 'Mentorship', category: 'Professional', type: 'categorical' },
  { id: '475', name: 'Mentor', category: 'Professional', type: 'categorical' },
  { id: '476', name: 'Mentee', category: 'Professional', type: 'categorical' },
  { id: '477', name: 'Networking', category: 'Professional', type: 'categorical' },
  { id: '478', name: 'LinkedIn Connections', category: 'Professional', type: 'range' },
  { id: '479', name: 'LinkedIn Followers', category: 'Professional', type: 'range' },
  { id: '480', name: 'LinkedIn Activity', category: 'Professional', type: 'categorical' },

  // Lifestyle (60 attributes)
  { id: '481', name: 'Hobbies', category: 'Lifestyle', type: 'categorical' },
  { id: '482', name: 'Interests', category: 'Lifestyle', type: 'categorical' },
  { id: '483', name: 'Activities', category: 'Lifestyle', type: 'categorical' },
  { id: '484', name: 'Sports', category: 'Lifestyle', type: 'categorical' },
  { id: '485', name: 'Favorite Sports', category: 'Lifestyle', type: 'categorical' },
  { id: '486', name: 'Sports Participation', category: 'Lifestyle', type: 'categorical' },
  { id: '487', name: 'Fitness Activities', category: 'Lifestyle', type: 'categorical' },
  { id: '488', name: 'Outdoor Activities', category: 'Lifestyle', type: 'categorical' },
  { id: '489', name: 'Indoor Activities', category: 'Lifestyle', type: 'categorical' },
  { id: '490', name: 'Travel Frequency', category: 'Lifestyle', type: 'categorical' },
  { id: '491', name: 'Travel Destinations', category: 'Lifestyle', type: 'categorical' },
  { id: '492', name: 'Travel Preferences', category: 'Lifestyle', type: 'categorical' },
  { id: '493', name: 'Vacation Style', category: 'Lifestyle', type: 'categorical' },
  { id: '494', name: 'Accommodation Preferences', category: 'Lifestyle', type: 'categorical' },
  { id: '495', name: 'Dining Preferences', category: 'Lifestyle', type: 'categorical' },
  { id: '496', name: 'Cuisine Preferences', category: 'Lifestyle', type: 'categorical' },
  { id: '497', name: 'Restaurant Preferences', category: 'Lifestyle', type: 'categorical' },
  { id: '498', name: 'Food Allergies', category: 'Lifestyle', type: 'categorical' },
  { id: '499', name: 'Dietary Restrictions', category: 'Lifestyle', type: 'categorical' },
  { id: '500', name: 'Cooking Frequency', category: 'Lifestyle', type: 'categorical' },
  { id: '501', name: 'Cooking Skill Level', category: 'Lifestyle', type: 'categorical' },
  { id: '502', name: 'Meal Planning', category: 'Lifestyle', type: 'categorical' },
  { id: '503', name: 'Grocery Shopping Frequency', category: 'Lifestyle', type: 'categorical' },
  { id: '504', name: 'Organic Food Preference', category: 'Lifestyle', type: 'categorical' },
  { id: '505', name: 'Local Food Preference', category: 'Lifestyle', type: 'categorical' },
  { id: '506', name: 'Sustainable Food', category: 'Lifestyle', type: 'categorical' },
  { id: '507', name: 'Fast Food Consumption', category: 'Lifestyle', type: 'categorical' },
  { id: '508', name: 'Fine Dining Frequency', category: 'Lifestyle', type: 'categorical' },
  { id: '509', name: 'Casual Dining Frequency', category: 'Lifestyle', type: 'categorical' },
  { id: '510', name: 'Takeout Frequency', category: 'Lifestyle', type: 'categorical' },
  { id: '511', name: 'Delivery Frequency', category: 'Lifestyle', type: 'categorical' },
  { id: '512', name: 'Coffee Consumption', category: 'Lifestyle', type: 'categorical' },
  { id: '513', name: 'Tea Consumption', category: 'Lifestyle', type: 'categorical' },
  { id: '514', name: 'Wine Consumption', category: 'Lifestyle', type: 'categorical' },
  { id: '515', name: 'Beer Consumption', category: 'Lifestyle', type: 'categorical' },
  { id: '516', name: 'Spirits Consumption', category: 'Lifestyle', type: 'categorical' },
  { id: '517', name: 'Cocktail Preferences', category: 'Lifestyle', type: 'categorical' },
  { id: '518', name: 'Bar Preferences', category: 'Lifestyle', type: 'categorical' },
  { id: '519', name: 'Nightlife Frequency', category: 'Lifestyle', type: 'categorical' },
  { id: '520', name: 'Entertainment Preferences', category: 'Lifestyle', type: 'categorical' },
  { id: '521', name: 'Event Attendance', category: 'Lifestyle', type: 'categorical' },
  { id: '522', name: 'Concert Attendance', category: 'Lifestyle', type: 'categorical' },
  { id: '523', name: 'Theater Attendance', category: 'Lifestyle', type: 'categorical' },
  { id: '524', name: 'Museum Attendance', category: 'Lifestyle', type: 'categorical' },
  { id: '525', name: 'Art Gallery Attendance', category: 'Lifestyle', type: 'categorical' },
  { id: '526', name: 'Sports Event Attendance', category: 'Lifestyle', type: 'categorical' },
  { id: '527', name: 'Festival Attendance', category: 'Lifestyle', type: 'categorical' },
  { id: '528', name: 'Convention Attendance', category: 'Lifestyle', type: 'categorical' },
  { id: '529', name: 'Volunteer Work', category: 'Lifestyle', type: 'categorical' },
  { id: '530', name: 'Volunteer Frequency', category: 'Lifestyle', type: 'categorical' },
  { id: '531', name: 'Charity Involvement', category: 'Lifestyle', type: 'categorical' },
  { id: '532', name: 'Community Involvement', category: 'Lifestyle', type: 'categorical' },
  { id: '533', name: 'Religious Participation', category: 'Lifestyle', type: 'categorical' },
  { id: '534', name: 'Spiritual Practices', category: 'Lifestyle', type: 'categorical' },
  { id: '535', name: 'Meditation', category: 'Lifestyle', type: 'categorical' },
  { id: '536', name: 'Yoga', category: 'Lifestyle', type: 'categorical' },
  { id: '537', name: 'Mindfulness', category: 'Lifestyle', type: 'categorical' },
  { id: '538', name: 'Wellness Practices', category: 'Lifestyle', type: 'categorical' },
  { id: '539', name: 'Self-Care Practices', category: 'Lifestyle', type: 'categorical' },
  { id: '540', name: 'Beauty Routine', category: 'Lifestyle', type: 'categorical' },

  // Technology (40 attributes)
  { id: '541', name: 'Device Ownership', category: 'Technology', type: 'categorical' },
  { id: '542', name: 'Smartphone Brand', category: 'Technology', type: 'categorical' },
  { id: '543', name: 'Smartphone Model', category: 'Technology', type: 'categorical' },
  { id: '544', name: 'Tablet Brand', category: 'Technology', type: 'categorical' },
  { id: '545', name: 'Laptop Brand', category: 'Technology', type: 'categorical' },
  { id: '546', name: 'Desktop Brand', category: 'Technology', type: 'categorical' },
  { id: '547', name: 'Operating System', category: 'Technology', type: 'categorical' },
  { id: '548', name: 'Mobile OS', category: 'Technology', type: 'categorical' },
  { id: '549', name: 'Browser', category: 'Technology', type: 'categorical' },
  { id: '550', name: 'Browser Version', category: 'Technology', type: 'categorical' },
  { id: '551', name: 'Internet Service Provider', category: 'Technology', type: 'categorical' },
  { id: '552', name: 'Internet Speed', category: 'Technology', type: 'categorical' },
  { id: '553', name: 'WiFi Network', category: 'Technology', type: 'categorical' },
  { id: '554', name: 'Smart Home Devices', category: 'Technology', type: 'categorical' },
  { id: '555', name: 'IoT Devices', category: 'Technology', type: 'categorical' },
  { id: '556', name: 'Wearable Devices', category: 'Technology', type: 'categorical' },
  { id: '557', name: 'Fitness Tracker', category: 'Technology', type: 'categorical' },
  { id: '558', name: 'Smartwatch', category: 'Technology', type: 'categorical' },
  { id: '559', name: 'VR Headset', category: 'Technology', type: 'categorical' },
  { id: '560', name: 'AR Device', category: 'Technology', type: 'categorical' },
  { id: '561', name: 'Gaming Console', category: 'Technology', type: 'categorical' },
  { id: '562', name: 'Gaming PC', category: 'Technology', type: 'categorical' },
  { id: '563', name: 'Streaming Device', category: 'Technology', type: 'categorical' },
  { id: '564', name: 'Smart TV', category: 'Technology', type: 'categorical' },
  { id: '565', name: 'Home Assistant', category: 'Technology', type: 'categorical' },
  { id: '566', name: 'Voice Assistant', category: 'Technology', type: 'categorical' },
  { id: '567', name: 'Cloud Storage Usage', category: 'Technology', type: 'categorical' },
  { id: '568', name: 'Cloud Provider', category: 'Technology', type: 'categorical' },
  { id: '569', name: 'Software Usage', category: 'Technology', type: 'categorical' },
  { id: '570', name: 'Productivity Software', category: 'Technology', type: 'categorical' },
  { id: '571', name: 'Creative Software', category: 'Technology', type: 'categorical' },
  { id: '572', name: 'Development Tools', category: 'Technology', type: 'categorical' },
  { id: '573', name: 'Programming Languages', category: 'Technology', type: 'categorical' },
  { id: '574', name: 'Framework Knowledge', category: 'Technology', type: 'categorical' },
  { id: '575', name: 'Database Knowledge', category: 'Technology', type: 'categorical' },
  { id: '576', name: 'Cloud Platform Knowledge', category: 'Technology', type: 'categorical' },
  { id: '577', name: 'Cybersecurity Awareness', category: 'Technology', type: 'categorical' },
  { id: '578', name: 'Privacy Settings', category: 'Technology', type: 'categorical' },
  { id: '579', name: 'Data Sharing Preferences', category: 'Technology', type: 'categorical' },
  { id: '580', name: 'App Usage', category: 'Technology', type: 'categorical' },

  // Marketing (40 attributes)
  { id: '581', name: 'Purchase Intent', category: 'Marketing', type: 'categorical' },
  { id: '582', name: 'Buying Stage', category: 'Marketing', type: 'categorical' },
  { id: '583', name: 'Purchase Timeline', category: 'Marketing', type: 'categorical' },
  { id: '584', name: 'Budget Range', category: 'Marketing', type: 'range' },
  { id: '585', name: 'Decision Maker', category: 'Marketing', type: 'categorical' },
  { id: '586', name: 'Influencer Status', category: 'Marketing', type: 'categorical' },
  { id: '587', name: 'Influence Score', category: 'Marketing', type: 'range' },
  { id: '588', name: 'Social Media Influence', category: 'Marketing', type: 'categorical' },
  { id: '589', name: 'Follower Count', category: 'Marketing', type: 'range' },
  { id: '590', name: 'Engagement Rate', category: 'Marketing', type: 'range' },
  { id: '591', name: 'Content Creator', category: 'Marketing', type: 'categorical' },
  { id: '592', name: 'Content Type', category: 'Marketing', type: 'categorical' },
  { id: '593', name: 'Content Frequency', category: 'Marketing', type: 'categorical' },
  { id: '594', name: 'Brand Affinity', category: 'Marketing', type: 'categorical' },
  { id: '595', name: 'Brand Loyalty', category: 'Marketing', type: 'categorical' },
  { id: '596', name: 'Brand Preferences', category: 'Marketing', type: 'categorical' },
  { id: '597', name: 'Product Preferences', category: 'Marketing', type: 'categorical' },
  { id: '598', name: 'Service Preferences', category: 'Marketing', type: 'categorical' },
  { id: '599', name: 'Price Sensitivity', category: 'Marketing', type: 'categorical' },
  { id: '600', name: 'Deal Seeking', category: 'Marketing', type: 'categorical' },
  { id: '601', name: 'Coupon Usage', category: 'Marketing', type: 'categorical' },
  { id: '602', name: 'Promotion Responsiveness', category: 'Marketing', type: 'categorical' },
  { id: '603', name: 'Email Marketing Engagement', category: 'Marketing', type: 'categorical' },
  { id: '604', name: 'SMS Marketing Engagement', category: 'Marketing', type: 'categorical' },
  { id: '605', name: 'Push Notification Engagement', category: 'Marketing', type: 'categorical' },
  { id: '606', name: 'Social Media Engagement', category: 'Marketing', type: 'categorical' },
  { id: '607', name: 'Display Ad Engagement', category: 'Marketing', type: 'categorical' },
  { id: '608', name: 'Video Ad Engagement', category: 'Marketing', type: 'categorical' },
  { id: '609', name: 'Search Ad Engagement', category: 'Marketing', type: 'categorical' },
  { id: '610', name: 'Retargeting Engagement', category: 'Marketing', type: 'categorical' },
  { id: '611', name: 'Affiliate Engagement', category: 'Marketing', type: 'categorical' },
  { id: '612', name: 'Referral Program Participation', category: 'Marketing', type: 'categorical' },
  { id: '613', name: 'Loyalty Program Participation', category: 'Marketing', type: 'categorical' },
  { id: '614', name: 'Rewards Program Participation', category: 'Marketing', type: 'categorical' },
  { id: '615', name: 'Customer Lifetime Value', category: 'Marketing', type: 'range' },
  { id: '616', name: 'Customer Acquisition Cost', category: 'Marketing', type: 'range' },
  { id: '617', name: 'Churn Risk', category: 'Marketing', type: 'categorical' },
  { id: '618', name: 'Retention Score', category: 'Marketing', type: 'range' },
  { id: '619', name: 'Upsell Potential', category: 'Marketing', type: 'categorical' },
  { id: '620', name: 'Cross-Sell Potential', category: 'Marketing', type: 'categorical' },
]

export const getAttributesByCategory = (category: AttributeCategory): Attribute[] => {
  return ALL_ATTRIBUTES.filter(attr => attr.category === category)
}

export const getCategoryStats = (selectedAttributeIds: string[]): Record<AttributeCategory, { total: number; selected: number }> => {
  const stats: Record<string, { total: number; selected: number }> = {}
  
  ATTRIBUTE_CATEGORIES.forEach(category => {
    const categoryAttrs = getAttributesByCategory(category)
    stats[category] = {
      total: categoryAttrs.length,
      selected: categoryAttrs.filter(attr => selectedAttributeIds.includes(attr.id)).length,
    }
  })
  
  return stats as Record<AttributeCategory, { total: number; selected: number }>
}
